### ISSUE TITLE
0.8.0 build failed use crystal 1.11.2 on arch linux latest.

### ISSUE THREAD

**Issue by zw963** [hugopl/tijolo#14] opened 2024-02-23 13:44 UTC
**Describe the bug**

```
 ╰─ $ make
shards install
Resolving dependencies
Fetching https://github.com/hugopl/fzy.git
Fetching https://github.com/hugopl/vte.cr.git
Fetching https://github.com/geopjr/libadwaita.cr.git
Fetching https://github.com/crystal-community/toml.cr.git
Fetching https://github.com/hugopl/gtk4.cr.git
Fetching https://github.com/hugopl/gi-crystal.git
Fetching https://github.com/hugopl/pango.cr.git
Fetching https://github.com/hugopl/harfbuzz.cr.git
Using fzy (0.5.5)
Using gi-crystal (0.22.1)
Using harfbuzz (0.2.0)
Using pango (0.3.1)
Using gtk4 (0.16.0)
Using libadwaita (1.0.0 at cffabb5)
Using toml (0.7.0)
Using vte (0.1.0)
./bin/gi-crystal
info - Starting at 2024-02-23 21:41:29 +08:00, project dir: /home/zw963/Crystal/git/tijolo
info - Gi-Crystal version 0.22.1, built with Crystal 1.11.2.
info - Generating bindings at /home/zw963/Crystal/git/tijolo/lib/gi-crystal/src/auto
info - Using binding config at /home/zw963/Crystal/git/tijolo/lib/gi-crystal/src/bindings/g_lib/binding.yml
info - Using binding config at /home/zw963/Crystal/git/tijolo/lib/gi-crystal/src/bindings/g_object/binding.yml
info - Using binding config at /home/zw963/Crystal/git/tijolo/lib/gi-crystal/src/bindings/gio/binding.yml
info - Using binding config at /home/zw963/Crystal/git/tijolo/lib/harfbuzz/src/bindings/harfbuzz/binding.yml
info - Using binding config at /home/zw963/Crystal/git/tijolo/lib/pango/src/bindings/pango/binding.yml
info - Using binding config at /home/zw963/Crystal/git/tijolo/lib/gtk4/src/bindings/gdk/binding.yml
info - Using binding config at /home/zw963/Crystal/git/tijolo/lib/gtk4/src/bindings/gsk/binding.yml
info - Using binding config at /home/zw963/Crystal/git/tijolo/lib/gtk4/src/bindings/gtk/binding.yml
info - Using binding config at /home/zw963/Crystal/git/tijolo/lib/libadwaita/src/bindings/binding.yml
info - Using binding config at /home/zw963/Crystal/git/tijolo/lib/vte/src/bindings/vte/binding.yml
info - Using binding config at /home/zw963/Crystal/git/tijolo/src/bindings/gtksource/binding.yml
warn - g_cancellable_connect - Callback without user_data!
warn - Gio::ActionEntry padding field - Unknown conversion to crystal for fixed size array.
warn - Gio::DBusInterfaceVTable padding field - Unknown conversion to crystal for fixed size array.
warn - Gio::DBusSubtreeVTable padding field - Unknown conversion to crystal for fixed size array.
info - HarfBuzz - No binding config found for freetype2-2.0.
warn - HarfBuzz - Interface constant not supported.
info - Pango - No binding config found for cairo-1.0.
info - Gdk - No binding config found for PangoCairo-1.0.
info - Gdk - No binding config found for GdkPixbuf-2.0.
warn - Gdk::TimeCoord axes field - Unknown conversion to crystal for fixed size array.
info - GdkPixbuf - No binding config found for GModule-2.0.
warn - gdk_pixbuf_get_options - Unknown conversion to crystal for GHash
info - Gsk - No binding config found for Graphene-1.0.
warn - gsk_border_node_get_widths - Unknown conversion to crystal for fixed size array.
warn - Boxed not working for enums
warn - Gtk::BuildableParser padding field - Unknown conversion to crystal for fixed size array.
shards build --release -Dpreview_mt -s
Dependencies are satisfied
Building: tijolo
Parse:                             00:00:00.000156437 (   1.07MB)
Semantic (top level):              00:00:00.831007745 ( 417.78MB)
Semantic (new):                    00:00:00.009540952 ( 425.78MB)
Semantic (type declarations):      00:00:00.281807884 ( 433.78MB)
Semantic (abstract def check):     00:00:00.021022366 ( 441.78MB)
Semantic (restrictions augmenter): 00:00:00.043025205 ( 441.78MB)
Semantic (ivars initializers):     00:00:00.059134669 ( 481.78MB)
Semantic (cvars initializers):     00:00:00.057166346 ( 529.78MB)
Error target tijolo failed to compile:
Showing last frame. Use --error-trace for full trace.

In src/text_view.cr:38:48

 38 | code_model.insert_text(res, text, iter.offset, len)
                                             ^-----
Error: expected argument #3 to 'EmptyCodeModel#insert_text' to be Int64, not Int32

Overloads are:
 - CodeModel#insert_text(source : Path, text : String, offset : Int64, len : Int64)

make: *** [Makefile:5: all] Error 1
```

Following is the backtrace:

<details>
<summary>back trace</summary>

```
Error target tijolo failed to compile:
In src/main.cr:34:23

 34 | app = Application.new
                        ^--
Error: instantiating 'Application.new()'


In src/application.cr:19:5

 19 | super(application_id: "io.github.hugopl.Tijolo", flags: flags)
      ^----
Error: instantiating 'super(application_id: String, flags: Gio::ApplicationFlags)'


In lib/gi-crystal/src/auto/adw-1/application.cr:112:64

 112 | ptr = LibGObject.g_object_new_with_properties(self.class.g_type, _n, _names, _values)
                                                                ^-----
Error: instantiating 'Application.g_type()'


In src/application.cr:8:1

 8 | class Application < Adw::Application
     ^
Error: expanding macro


There was a problem expanding macro 'inherited'

Called macro defined in lib/gi-crystal/src/bindings/g_object/object.cr:63:5

 63 | macro inherited

Which expanded to:

 >   1 |
 >   2 |         macro method_added(method)
 >   3 |
 >   4 |             {% if method.annotation(GObject::Virtual) %}
 >   5 |               {% vfunc_name = (method.annotation(GObject::Virtual))[:name] || (method.name.gsub(/^do_/, "")) %}
 >   6 |               {% if (method.annotation(GObject::Virtual))[:unsafe] %}
 >   7 |                 {% vfunc_name = "unsafe_#{vfunc_name.id}" %}
 >   8 |               {% end %}
 >   9 |               _register_{{ vfunc_name.id }}_vfunc({{ method.name }})
 >  10 |             {% end %}
 >  11 |
 >  12 |         end
 >  13 |
 >  14 |         # GType for the new created type
 >  15 |         @@_g_type : UInt64 = 0
 >  16 |
 >  17 |         # ParamSpec pointers for the GObject properties in the object
 >  18 |         @@_g_param_specs = Pointer(LibGObject::ParamSpec*).null
 >  19 |
 >  20 |         @_g_retainer : Void* = Pointer(Void).null
 >  21 |
 >  22 |         def self.g_type : UInt64
 >  23 |           if LibGLib.g_once_init_enter(pointerof(@@_g_type)) != 0
 >  24 |             g_type = Adw::Application._register_derived_type("Application",
 >  25 |               ->_class_init(Pointer(LibGObject::TypeClass), Pointer(Void)),
 >  26 |               ->_instance_init(Pointer(LibGObject::TypeInstance), Pointer(LibGObject::TypeClass)))
 >  27 |
 >  28 |             LibGLib.g_once_init_leave(pointerof(@@_g_type), g_type)
 >  29 |             self._install_ifaces
 >  30 |           end
 >  31 |
 >  32 |           @@_g_type
 >  33 |         end
 >  34 |
 >  35 |         # :nodoc:
 >  36 |         def self._class_init(klass : Pointer(LibGObject::TypeClass), user_data : Pointer(Void)) : Nil
 >  37 |
 >  38 |             {% if true %}
 >  39 |               {% instance_vars = @type.instance_vars.select(&.annotation(GObject::Property)) %}
 >  40 |
 >  41 |               @@_g_param_specs = Pointer(LibGObject::ParamSpec*).malloc({{ instance_vars.size }})
 >  42 |               {% for var, i in instance_vars %}
 >  43 |                 {% property = var.annotation(GObject::Property) %}
 >  44 |                 name = {{ (var.name.gsub(/\_/, "-")).stringify }}.to_unsafe
 >  45 |                 nick = {{ property["nick"] }}.try(&.to_unsafe) || Pointer(LibC::Char).null
 >  46 |                 blurb = {{ property["blurb"] }}.try(&.to_unsafe) || Pointer(LibC::Char).null
 >  47 |
 >  48 |                 {% has_getter = (@type.has_method?(var.name.stringify)) || (@type.has_method?(var.name.stringify + "?")) %}
 >  49 |                 {% has_setter = @type.has_method?("#{var.name}=") %}
 >  50 |                 {% unless has_getter || has_setter
 >  51 |   raise("GObject properties need to have a getter and/or a setter")
 >  52 | end %}
 >  53 |
 >  54 |                 flags = GObject::ParamFlags::StaticName | GObject::ParamFlags::StaticBlurb | GObject::ParamFlags::ExplicitNotify
 >  55 |                 flags |= GObject::ParamFlags::Deprecated unless {{ !(!(var.annotation(Deprecated))) }}
 >  56 |                 flags |= GObject::ParamFlags::Readable if {{ has_getter }}
 >  57 |                 flags |= GObject::ParamFlags::Writable if {{ has_setter }}
 >  58 |
 >  59 |                 {% other_args = property.named_args.to_a.select do |arg|
 >  60 |   (["min", "max", "default"] of ::String).includes?(arg[0].stringify)
 >  61 | end %}
 >  62 |                 # Finally register the type to GLib.
 >  63 |                 # The given varible name has its underscores converted to dashes.
 >  64 |                 pspec = GObject.create_param_spec({{ var.type }}, name, nick, blurb, flags, {{ other_args.map do |tuple|
 >  65 |   "#{tuple[0]}: #{tuple[1]}".id
 >  66 | end.splat }})
 >  67 |                 @@_g_param_specs[{{ i }}] = pspec.as(LibGObject::ParamSpec*)
 >  68 |                 LibGObject.g_object_class_install_property(klass, {{ i + 1 }}, pspec)
 >  69 |               {% end %}
 >  70 |             {% end %}
 >  71 |
 >  72 |         end
 >  73 |
 >  74 |         # :nodoc:
 >  75 |         def self._g_toggle_notify(object : Void*, _gobject : Void*, is_last_ref : Int32) : Nil
 >  76 |           return if object.null?
 >  77 |           is_last_ref = GICrystal.to_bool(is_last_ref)
 >  78 |
 >  79 |           if is_last_ref
 >  80 |             # This branch is entered once there are no additional references to this GObject left.
 >  81 |             # Remove the toggle ref so it can be garbage collected if there are no references to this object in crystal.
 >  82 |
 >  83 |             GICrystal::ToggleRefManager.deregister(object.as(self).@_g_retainer)
 >  84 |           else
 >  85 |             # This branch is entered once at least one additional reference to this GObject has been established.
 >  86 |             # It must now be protected from being garbage collected.
 >  87 |
 >  88 |             (object + offsetof(self, @_g_retainer)).as(Void**).value = GICrystal::ToggleRefManager.register(object)
 >  89 |           end
 >  90 |         end
 >  91 |         private G_TOGGLE_NOTIFY__ = ->_g_toggle_notify(Void*, Void*, Int32)
 >  92 |
 >  93 |         # :nodoc:
 >  94 |         @[GObject::Virtual(unsafe: true, name: "get_property")]
 >  95 |         def _get_property(property_id : UInt32, gvalue : Void*, param_spec : Void*) : Nil
 >  96 |
 >  97 |             {% if true %}
 >  98 |               {% instance_vars = @type.instance_vars.select(&.annotation(GObject::Property)) %}
 >  99 |
 > 100 |               case property_id
 > 101 |               {% for var, i in instance_vars %}
 > 102 |                 {% if @type.has_method?(var.name.stringify) %}
 > 103 |                   when {{ i + 1 }}
 > 104 |                     GObject::Value.set_g_value(gvalue.as(LibGObject::Value*), self.{{ var }})
 > 105 |                 {% end %}
 > 106 |               {% end %}
 > 107 |               end
 > 108 |             {% end %}
 > 109 |
 > 110 |         end
 > 111 |
 > 112 |         # :nodoc:
 > 113 |         @[GObject::Virtual(unsafe: true, name: "set_property")]
 > 114 |         def _set_property(property_id : UInt32, gvalue : Void*, param_spec : Void*) : Nil
 > 115 |
 > 116 |             {% if true %}
 > 117 |               {% instance_vars = @type.instance_vars.select(&.annotation(GObject::Property)) %}
 > 118 |
 > 119 |               case property_id
 > 120 |               {% for var, i in instance_vars %}
 > 121 |                 {% if @type.has_method?("#{var.name}=") %}
 > 122 |                   when {{ i + 1 }}
 > 123 |                     {% if var.type.nilable? && var.type.union_types.size > 2 %}
 > 124 |                       {% raise("Union types are not supported in GObject properties") %}
 > 125 |                     {% end %}
 > 126 |
 > 127 |                     {% var_type = var.type.union_types.reject do |t|
 > 128 |   t == Nil
 > 129 | end.first %}
 > 130 |
 > 131 |                     {% if var_type < GObject::Object %}
 > 132 |                       raw = GObject::Value.raw(GObject::TYPE_OBJECT, gvalue)
 > 133 |                       {% if var.type.nilable? %}
 > 134 |                         raw_obj = raw.as?(GObject::Object)
 > 135 |                         self.{{ var }} = raw_obj.nil? ? nil : {{ var_type }}.cast(raw_obj)
 > 136 |                       {% else %}
 > 137 |                         self.{{ var }} = {{ var_type }}.cast(raw.as(GObject::Object))
 > 138 |                       {% end %}
 > 139 |                     {% else %}{% if var_type < Enum %}
 > 140 |                       {% if var_type.annotation(Flags) %}
 > 141 |                         raw = GObject::Value.raw(GObject::TYPE_FLAGS, gvalue)
 > 142 |                         self.{{ var }} = raw.as(UInt32).unsafe_as({{ var_type }})
 > 143 |                       {% else %}
 > 144 |                         raw = GObject::Value.raw(GObject::TYPE_ENUM, gvalue)
 > 145 |                         self.{{ var }} = raw.as(Int32).unsafe_as({{ var_type }})
 > 146 |                       {% end %}
 > 147 |                     {% else %}
 > 148 |                       raw = GObject::Value.raw({{ var_type }}.g_type, gvalue)
 > 149 |                       self.{{ var }} = raw.as({{ var_type }})
 > 150 |                     {% end %}{% end %}
 > 151 |                 {% end %}
 > 152 |               {% end %}
 > 153 |               end
 > 154 |             {% end %}
 > 155 |
 > 156 |         end
 > 157 |
 > 158 |         private macro _emit_notify_signal(arg)
 > 159 |
 > 160 |             {% if true %}
 > 161 |               {% instance_vars = @type.instance_vars.select(&.annotation(GObject::Property)) %}
 > 162 |
 > 163 |               {% for var, i in instance_vars %}
 > 164 |                 {% if var.name == arg.id %}
 > 165 |                   LibGObject.g_object_notify_by_pspec(self, @@_g_param_specs[{{ i }}])
 > 166 |                 {% end %}
 > 167 |               {% end %}
 > 168 |             {% end %}
 > 169 |
 > 170 |         end
 > 171 |
 > 172 |         # :nodoc:
 > 173 |         # Mostly copied from crystal source
 > 174 |         macro setter(*names)
 > 175 |
 > 176 |             {% for name in names %}
 > 177 |               {% if name.is_a?(TypeDeclaration) %}
 > 178 |                 @{{ name }}
 > 179 |
 > 180 |                 def {{ name.var.id }}=(@{{ name.var.id }} : {{ name.type }})
 > 181 |                   _emit_notify_signal({{ name.var.id }})
 > 182 |                 end
 > 183 |               {% else %}{% if name.is_a?(Assign) %}
 > 184 |                 @{{ name }}
 > 185 |
 > 186 |                 def {{ name.target.id }}=(@{{ name.target.id }})
 > 187 |                   _emit_notify_signal({{ name.target.id }})
 > 188 |                 end
 > 189 |               {% else %}
 > 190 |                 def {{ name.id }}=(@{{ name.id }})
 > 191 |                   _emit_notify_signal({{ name.id }})
 > 192 |                 end
 > 193 |               {% end %}{% end %}
 > 194 |             {% end %}
 > 195 |
 > 196 |         end
 > 197 |
 > 198 |         # :nodoc:
 > 199 |         # Mostly copied from crystal source
 > 200 |         macro property(*names, &block)
 > 201 |
 > 202 |             {% if block %}
 > 203 |               {% if names.size != 1 %}
 > 204 |                 {{ raise("Only one argument can be passed to `property` with a block") }}
 > 205 |               {% end %}
 > 206 |
 > 207 |               {% name = names[0] %}
 > 208 |
 > 209 |               {% if name.is_a?(TypeDeclaration) %}
 > 210 |                 @{{ name.var.id }} : {{ name.type }}?
 > 211 |
 > 212 |                 def {{ name.var.id }} : {{ name.type }}
 > 213 |                   if (value = @{{ name.var.id }}).nil?
 > 214 |                     @{{ name.var.id }} = {{ yield }}
 > 215 |                     _emit_notify_signal({{ name.var.id }})
 > 216 |                   else
 > 217 |                     value
 > 218 |                   end
 > 219 |                 end
 > 220 |
 > 221 |                 def {{ name.var.id }}=(@{{ name.var.id }} : {{ name.type }})
 > 222 |                   _emit_notify_signal({{ name.var.id }})
 > 223 |                 end
 > 224 |               {% else %}
 > 225 |                 def {{ name.id }}
 > 226 |                   if (value = @{{ name.id }}).nil?
 > 227 |                     @{{ name.id }} = {{ yield }}
 > 228 |                     _emit_notify_signal({{ name.id }})
 > 229 |                   else
 > 230 |                     value
 > 231 |                   end
 > 232 |                 end
 > 233 |
 > 234 |                 def {{ name.id }}=(@{{ name.id }})
 > 235 |                   _emit_notify_signal({{ name.id }})
 > 236 |                 end
 > 237 |               {% end %}
 > 238 |             {% else %}
 > 239 |               {% for name in names %}
 > 240 |                 {% if name.is_a?(TypeDeclaration) %}
 > 241 |                   @{{ name }}
 > 242 |
 > 243 |                   def {{ name.var.id }} : {{ name.type }}
 > 244 |                     @{{ name.var.id }}
 > 245 |                   end
 > 246 |
 > 247 |                   def {{ name.var.id }}=(@{{ name.var.id }} : {{ name.type }})
 > 248 |                     _emit_notify_signal({{ name.var.id }})
 > 249 |                   end
 > 250 |                 {% else %}{% if name.is_a?(Assign) %}
 > 251 |                   @{{ name }}
 > 252 |
 > 253 |                   def {{ name.target.id }}
 > 254 |                     @{{ name.target.id }}
 > 255 |                   end
 > 256 |
 > 257 |                   def {{ name.target.id }}=(@{{ name.target.id }})
 > 258 |                     _emit_notify_signal({{ name.target.id }})
 > 259 |                   end
 > 260 |                 {% else %}
 > 261 |                   def {{ name.id }}
 > 262 |                     @{{ name.id }}
 > 263 |                   end
 > 264 |
 > 265 |                   def {{ name.id }}=(@{{ name.id }})
 > 266 |                     _emit_notify_signal({{ name.id }})
 > 267 |                   end
 > 268 |                 {% end %}{% end %}
 > 269 |               {% end %}
 > 270 |             {% end %}
 > 271 |
 > 272 |         end
 > 273 |
 > 274 |         # :nodoc:
 > 275 |         # Mostly copied from crystal source
 > 276 |         macro property!(*names)
 > 277 |
 > 278 |             getter! {{ names.splat }}
 > 279 |
 > 280 |             {% for name in names %}
 > 281 |               {% if name.is_a?(TypeDeclaration) %}
 > 282 |                 def {{ name.var.id }}=(@{{ name.var.id }} : {{ name.type }})
 > 283 |                   _emit_notify_signal({{ name.var.id }})
 > 284 |                 end
 > 285 |               {% else %}
 > 286 |                 def {{ name.id }}=(@{{ name.id }})
 > 287 |                   _emit_notify_signal({{ name.id }})
 > 288 |                 end
 > 289 |               {% end %}
 > 290 |             {% end %}
 > 291 |
 > 292 |         end
 > 293 |
 > 294 |         # :nodoc:
 > 295 |         # Mostly copied from crystal source
 > 296 |         macro property?(*names, &block)
 > 297 |
 > 298 |             {% if block %}
 > 299 |               {% if names.size != 1 %}
 > 300 |                 {{ raise("Only one argument can be passed to `property?` with a block") }}
 > 301 |               {% end %}
 > 302 |
 > 303 |               {% name = names[0] %}
 > 304 |
 > 305 |               {% if name.is_a?(TypeDeclaration) %}
 > 306 |                 @{{ name.var.id }} : {{ name.type }}?
 > 307 |
 > 308 |                 def {{ name.var.id }}? : {{ name.type }}
 > 309 |                   if (value = @{{ name.var.id }}).nil?
 > 310 |                     @{{ name.var.id }} = {{ yield }}
 > 311 |                     _emit_notify_signal({{ name.var.id }})
 > 312 |                   else
 > 313 |                     value
 > 314 |                   end
 > 315 |                 end
 > 316 |
 > 317 |                 def {{ name.var.id }}=(@{{ name.var.id }} : \{{name.type}})
 > 318 |                   _emit_notify_signal({{ name.var.id }})
 > 319 |                 end
 > 320 |               {% else %}
 > 321 |                 def {{ name.id }}?
 > 322 |                   if (value = @{{ name.id }}).nil?
 > 323 |                     @{{ name.id }} = {{ yield }}
 > 324 |                     _emit_notify_signal({{ name.id }})
 > 325 |                   else
 > 326 |                     value
 > 327 |                   end
 > 328 |                 end
 > 329 |
 > 330 |                 def {{ name.id }}=(@{{ name.id }})
 > 331 |                   _emit_notify_signal({{ name.id }})
 > 332 |                 end
 > 333 |               {% end %}
 > 334 |             {% else %}
 > 335 |               {% for name in names %}
 > 336 |                 {% if name.is_a?(TypeDeclaration) %}
 > 337 |                   @{{ name }}
 > 338 |
 > 339 |                   def {{ name.var.id }}? : {{ name.type }}
 > 340 |                     @{{ name.var.id }}
 > 341 |                   end
 > 342 |
 > 343 |                   def {{ name.var.id }}=(@{{ name.var.id }} : {{ name.type }})
 > 344 |                     _emit_notify_signal({{ name.var.id }})
 > 345 |                   end
 > 346 |                 {% else %}{% if name.is_a?(Assign) %}
 > 347 |                   @{{ name }}
 > 348 |
 > 349 |                   def {{ name.target.id }}?
 > 350 |                     @{{ name.target.id }}
 > 351 |                   end
 > 352 |
 > 353 |                   def {{ name.target.id }}=(@{{ name.target.id }})
 > 354 |                     _emit_notify_signal({{ name.target.id }})
 > 355 |                   end
 > 356 |                 {% else %}
 > 357 |                   def {{ name.id }}?
 > 358 |                     @{{ name.id }}
 > 359 |                   end
 > 360 |
 > 361 |                   def {{ name.id }}=(@{{ name.id }})
 > 362 |                     _emit_notify_signal({{ name.id }})
 > 363 |                   end
 > 364 |                 {% end %}{% end %}
 > 365 |               {% end %}
 > 366 |             {% end %}
 > 367 |
 > 368 |         end
 > 369 |
 > 370 |         # :nodoc:
 > 371 |         def self._instance_init(instance : Pointer(LibGObject::TypeInstance), type : Pointer(LibGObject::TypeClass)) : Nil
 > 372 |         end
 > 373 |
 > 374 |         # :nodoc:
 > 375 |         def self._install_ifaces
 > 376 |
 > 377 |             {% for ancestor in @type.ancestors.uniq %}
 > 378 |               {% if ancestor.module? && (ancestor.class.has_method?("g_type")) %}
 > 379 |                 closure = ->_install_iface_{{ ancestor.name.gsub(/::/, "__") }}(Pointer(LibGObject::TypeInterface))
 > 380 |                 interface_info = LibGObject::InterfaceInfo.new()
 > 381 |                 interface_info.interface_init = closure.pointer
 > 382 |                 interface_info.interface_finalize = Pointer(Void).null
 > 383 |                 interface_info.interface_data = closure.closure_data
 > 384 |                 LibGObject.g_type_add_interface_static(g_type, {{ ancestor }}.g_type, pointerof(interface_info))
 > 385 |               {% end %}
 > 386 |             {% end %}
 > 387 |
 > 388 |         end
 > 389 |
 > 390 |         # Cast a `GObject::Object` to this type, returns nil if cast can't be made.
 > 391 |         def self.cast?(obj : GObject::Object) : self?
 > 392 |           new(obj.to_unsafe, :none) unless LibGObject.g_type_check_instance_is_a(obj, g_type).zero?
 > 393 |         end
 > 394 |
 > 395 |         # A hook to be executed after the underlying gobject has been initialized.
 > 396 |         #
 > 397 |         # This specific implementation turns a normal reference into a toggle reference.
 > 398 |         private def _after_init : Nil
 > 399 |           # Set toggle ref to protect the crystal object from the garbage collector while in C.
 > 400 |
 > 401 |           self.class._g_toggle_notify(self.as(Void*), @pointer, 0)
 > 402 |           LibGObject.g_object_add_toggle_ref(@pointer, G_TOGGLE_NOTIFY__, self.as(Void*))
 > 403 |           LibGObject.g_object_unref(@pointer)
 > 404 |         end
 > 405 |
 > 406 |         # :nodoc:
 > 407 |         def finalize
 > 408 |
 > 409 |
 > 410 |           LibGObject.g_object_set_qdata(self, GICrystal::INSTANCE_QDATA_KEY, Pointer(Void).null)
 > 411 |           LibGObject.g_object_remove_toggle_ref(self, G_TOGGLE_NOTIFY__, self.as(Void*))
 > 412 |         end
 > 413 |
 > 414 |         # :nodoc:
 > 415 |         def self.new(pointer, transfer : GICrystal::Transfer) : self
 > 416 |           # This overrides the `initialize(pointer, transfer : GICrystal::Transfer)`
 > 417 |           # method because we must make sure there is never a second crystal object for this gobject.
 > 418 |
 > 419 |           instance = LibGObject.g_object_get_qdata(pointer, GICrystal::INSTANCE_QDATA_KEY)
 > 420 |           raise "Could not retrieve crystal instance!" if instance.null?
 > 421 |
 > 422 |           LibGObject.g_object_ref_sink(pointer) if transfer.none? || LibGObject.g_object_is_floating(pointer) == 1
 > 423 |           LibGObject.g_object_unref(pointer)
 > 424 |
 > 425 |           instance.as(self)
 > 426 |         end
 > 427 |
 > 428 |
Error: instantiating '_class_init(Pointer(LibGObject::TypeClass), Pointer(Void))'


There was a problem expanding macro 'method_added'

Called macro defined in macro 'inherited'

 2 | macro method_added(method)

Which expanded to:

 > 1 |
 > 2 |
 > 3 |
 > 4 |
 > 5 |               _register_handle_local_options_vfunc(handle_local_options)
 > 6 |
 > 7 |
 > 8 |
Error: expanding macro


There was a problem expanding macro '_register_handle_local_options_vfunc'

Called macro defined in lib/gi-crystal/src/auto/gio-2.0/application.cr:1383:13

 1383 | private macro _register_handle_local_options_vfunc(impl_method_name)

Which expanded to:

 >  1 |       private def self._vfunc_handle_local_options(__temp_214 : Pointer(Void), lib_options :  Pointer(Void), ) : Int32
 >  2 |         # @options:
 >  3 |
 >  4 | # Generator::BuiltInTypeArgPlan
 >  5 | options=GLib::VariantDict.new(lib_options, GICrystal::Transfer::None)
 >  6 |
 >  7 |
 >  8 |         __temp_215 = LibGObject.g_object_get_qdata(__temp_214, GICrystal::INSTANCE_QDATA_KEY)
 >  9 |         raise GICrystal::ObjectCollectedError.new if __temp_215.null?
 > 10 |
 > 11 |         __temp_216 = __temp_215.as(self).handle_local_options(options)
 > 12 |
 > 13 |         __temp_216
 > 14 |       end
 > 15 |
 > 16 |       def self._class_init(type_struct : Pointer(LibGObject::TypeClass), user_data : Pointer(Void)) : Nil
 > 17 |         vfunc_ptr = (type_struct.as(Pointer(Void)) + 240).as(Pointer(Pointer(Void)))
 > 18 |         vfunc_ptr.value = (->_vfunc_handle_local_options(Pointer(Void), Pointer(Void))).pointer
 > 19 |         previous_def
 > 20 |       end
 > 21 |
Error: instantiating 'previous_def(Pointer(LibGObject::TypeClass), Pointer(Void))'


There was a problem expanding macro 'method_added'

Called macro defined in macro 'inherited'

 2 | macro method_added(method)

Which expanded to:

 > 1 |
 > 2 |
 > 3 |
 > 4 |
 > 5 |               _register_activate_vfunc(activate)
 > 6 |
 > 7 |
 > 8 |
Error: expanding macro


There was a problem expanding macro '_register_activate_vfunc'

Called macro defined in lib/gi-crystal/src/auto/gio-2.0/application.cr:1034:13

 1034 | private macro _register_activate_vfunc(impl_method_name)

Which expanded to:

 >  1 |       private def self._vfunc_activate(__temp_211 : Pointer(Void), ) : Void
 >  2 |
 >  3 |
 >  4 |         __temp_212 = LibGObject.g_object_get_qdata(__temp_211, GICrystal::INSTANCE_QDATA_KEY)
 >  5 |         raise GICrystal::ObjectCollectedError.new if __temp_212.null?
 >  6 |
 >  7 |         __temp_213 = __temp_212.as(self).activate()
 >  8 |
 >  9 |         __temp_213
 > 10 |       end
 > 11 |
 > 12 |       def self._class_init(type_struct : Pointer(LibGObject::TypeClass), user_data : Pointer(Void)) : Nil
 > 13 |         vfunc_ptr = (type_struct.as(Pointer(Void)) + 144).as(Pointer(Pointer(Void)))
 > 14 |         vfunc_ptr.value = (->_vfunc_activate(Pointer(Void))).pointer
 > 15 |         previous_def
 > 16 |       end
 > 17 |
Error: instantiating '_vfunc_activate(Pointer(Void))'


There was a problem expanding macro 'method_added'

Called macro defined in macro 'inherited'

 2 | macro method_added(method)

Which expanded to:

 > 1 |
 > 2 |
 > 3 |
 > 4 |
 > 5 |               _register_activate_vfunc(activate)
 > 6 |
 > 7 |
 > 8 |
Error: expanding macro


There was a problem expanding macro '_register_activate_vfunc'

Called macro defined in lib/gi-crystal/src/auto/gio-2.0/application.cr:1034:13

 1034 | private macro _register_activate_vfunc(impl_method_name)

Which expanded to:

 >  1 |       private def self._vfunc_activate(__temp_211 : Pointer(Void), ) : Void
 >  2 |
 >  3 |
 >  4 |         __temp_212 = LibGObject.g_object_get_qdata(__temp_211, GICrystal::INSTANCE_QDATA_KEY)
 >  5 |         raise GICrystal::ObjectCollectedError.new if __temp_212.null?
 >  6 |
 >  7 |         __temp_213 = __temp_212.as(self).activate()
 >  8 |
 >  9 |         __temp_213
 > 10 |       end
 > 11 |
 > 12 |       def self._class_init(type_struct : Pointer(LibGObject::TypeClass), user_data : Pointer(Void)) : Nil
 > 13 |         vfunc_ptr = (type_struct.as(Pointer(Void)) + 144).as(Pointer(Pointer(Void)))
 > 14 |         vfunc_ptr.value = (->_vfunc_activate(Pointer(Void))).pointer
 > 15 |         previous_def
 > 16 |       end
 > 17 |
Error: instantiating 'Application#activate()'


In src/application.cr:52:14

 52 | window = create_project_window(Project.new)
               ^--------------------
Error: instantiating 'create_project_window(Project)'


In src/application.cr:111:32

 111 | window = ApplicationWindow.new(self, project)
                                  ^--
Error: instantiating 'ApplicationWindow.new(Application, Project)'


In src/application_window.cr:50:5

 50 | setup_actions(application.settings)
      ^------------
Error: instantiating 'setup_actions(Gio::Settings)'


In src/application_window.cr:163:41

 163 | new_file:                ->new_file,
                                ^-------
Error: instantiating 'new_file()'


In src/application_window.cr:344:36

 344 | view_manager.add_view(TextView.new)
                                      ^--
Error: instantiating 'TextView.new()'


In src/text_view.cr:38:48

 38 | code_model.insert_text(res, text, iter.offset, len)
                                             ^-----
Error: expected argument #3 to 'EmptyCodeModel#insert_text' to be Int64, not Int32

Overloads are:
 - CodeModel#insert_text(source : Path, text : String, offset : Int64, len : Int64)
```
</details>

**Environment (please complete the following information):**
 - OS: Arch latest
 - GTK Version:  gtk3 1:3.24.41-1 gtk4 1:4.12.5-1
 - Crystal 1.11.2

**Additional context**
Wayland + GNOME 45

**Comment by hugopl** [comment] 2024-02-24 01:43
ouch, I'll check this next days, and check why it works here, archlinux too.

**Comment by zw963** [comment] 2024-02-24 07:00
more dependencies details:

```
 ╰─ $ pacman -Q |grep -E 'gtk4|libadwaita|gtksourceview5|vte4'
colord-gtk4 0.3.0-2
gtk4 1:4.12.5-1
gtksourceview5 5.10.0-1
libadwaita 1:1.4.3-1
libnma-gtk4 1.10.6-2
libportal-gtk4 0.7.1-2
vte4 0.74.2-1
```

**Comment by hugopl** [comment] 2024-02-25 21:03
It compiles fine with Crystal 1.11.1 here, maybe a 1.11.2 regression?

```
$ pacman -Q |/bin/grep -E 'gtk4|libadwaita|gtksourceview5|vte4'
colord-gtk4 0.3.0-2
gtk4 1:4.12.5-1
gtk4-demos 1:4.12.5-1
gtk4-docs 1:4.12.5-1
gtksourceview5 5.10.0-1
libadwaita 1:1.4.3-1
libadwaita-demos 1:1.4.3-1
libadwaita-docs 1:1.4.3-1
libnma-gtk4 1.10.6-2
libportal-gtk4 0.7.1-2
vte4 0.74.2-1
```

**Comment by zw963** [comment] 2024-02-26 06:56
Oops, i know why.

```sh
 ╰─ $ echo $CRYSTAL_OPTS
-Dstrict_multi_assign -Dno_number_autocast -Duse_pcre2 -Dpreview_overload_order
```

It can build successful if unset CRYSTAL_OPTS, it caused by `-Dno_number_autocast `.

Do you consider fix that?

**Comment by hugopl** [comment] 2024-02-26 12:56
Yes I do, it's always good to be prepared for crystal 2.x

**Comment by hugopl** [comment] 2024-02-26 18:07
I just read the issue with calm now, I like number auto-cast and ses no harm in using it, I added some other flags but kept without `-Dno_number_autocast`

It's defined in MakeFile as:
`CR_FLAGS ?= -Dpreview_mt -Dstrict_multi_assign -Duse_pcre2 -Dpreview_overload_order`

**Comment by hugopl** [comment] 2024-02-26 18:11
So I'll close this, BTW I don't think it's a good idea to keep these flags system wide, since they can break (as show here) the compilation of other applications that aren't broke.

And thanks for trying it out and reporting the issue!

**Closed as completed by hugopl** 2024-02-26 18:11 UTC

**Comment by zw963** [comment] 2024-02-27 11:34
BTW, you don't need the `-Dpreview_mt` in [this](https://github.com/hugopl/tijolo/blob/main/Makefile#L6) line for now.
